export const COLLEAGUE_OPTIONS = [
  'Claire Smith',
  'Daire Boyle',
  'Duc Tran',
  'Elisa Thouverai',
  'Geoff Smith',
  'Jack Petterson',
  'Lefteris Mamais',
  'Michal Salini',
  'Michelle Hermes',
  'Monica Miguel-Lago',
  'Natalia Kobliuk',
  'Phil Harwood',
  'Ruuta Skujina',
  'Tanya Walker',
  'Tim Heijmann',
];

export const SOURCE_OF_CONTACT_OPTIONS = [
  'Internal',
  'Inherited',
  'Events',
  'Referral',
  'Direct contact',
  'Webform',
];

export const LEAD_STATUS_OPTIONS = [
  'Active with SEF',
  'Contact with SEF',
  'Aware of SEF',
  'New contact',
];

export const STAKEHOLDER_TYPE_OPTIONS = [
  'ESA / SEF',
  'EO Service Provider',
  'Non-EO Service Provider',
  'Non-EO Research',
  'Policy Maker',
  'Policy Regulator/Enforcer',
  'Policy Implementer',
  'Interest Group',
  'Other',
];

export const ENGAGEMENT_TYPE_OPTIONS = [
  'Technical support',
  'Requirements gathering',
  'Coordination',
  'Training',
  'Outreach',
];

export const EVENT_TYPE_OPTIONS = [
  'Conference',
  'Workshop',
  'Webinar',
  'Meeting',
  'Other',
];

export const REQUIREMENT_CATEGORY_OPTIONS = [
  'Functional requirement',
  'Technical requirement',
  'Other requirement',
];

export const STAKEHOLDER_PRIORITY_OPTIONS = [
  'High priority',
  'Nice to have',
  'Fully addressed',
  'Partially addressed',
];

export const TIMESCALE_OPTIONS = [
  'Short term: 1-5 years',
  'Medium term: 5-10 years',
  'Long term: 10+ years',
];

export const SEF_THEME_OPTIONS = [
  'Ecosystem and Biodiversity',
  'Carbon, Energy and the Green Transition',
  'Sustainable Development Goals',
  'Food Systems',
];

export const SECTOR_OPTIONS = [
  'Agriculture',
  'Banking & Finance',
  'Carbon markets',
  'Climate action & climate',
  'Communications & connectivity',
  'Construction',
  'Education, training & research',
  'Emergency & social protection',
  'Environment, biodiversity & pollution',
  'EO & Remote sensing',
  'Fisheries',
  'Forestry',
  'Healthcare',
  'Humanitarian operations',
  'ICT, knowledge & digital interfaces',
  'Insurance & real estate',
  'Leisure',
  'Local & regional planning',
  'Marine & maritime',
  'Meteorology & climate monitoring',
  'Multiple',
  'Nature-based solutions',
  'News & media',
  'Oil & gas',
  'Other renewable energy',
  'Raw materials',
  'Renewable energy',
  'Retail & geo-marketing',
  'Security, defence & military',
  'Smart cities',
  'Solar renewable energy',
  'Transport & Logistics',
  'Travel & tourism',
  'Utilities & supplies',
  'Wind renewable energy',
];

export const APPLICATION_AREA_OPTIONS = [
  'Agriculture',
  'Assess & monitor coastal water quality',
  'Assess & monitor wetlands',
  'Assess and monitor crop disease and stress',
  'Assess and monitor volcanic activity',
  'Assess and monitor water bodies',
  'Assess changes in the carbon balance',
  'Assess climate change risk & climate forcing',
  'Assess crop damage due to storms',
  'Assess damage from earthquakes',
  'Assess damage from industrial accidents',
  'Assess deforestation / forest degradation',
  'Assess environmental impact of farming',
  'Assess environmental impact of forestry',
  'Assess environmental impact of human activities',
  'Assess forest damage due to storms or insects',
  'Assess ground water and run-off',
  'Assess land accounting (value, ownership, type, use)',
  'Assess land ecosystems and biodiversity',
  'Assess pressures on populations and monitor humanitarian movement',
  'Assess, monitor & manage forest resources',
  'Asset infrastructure monitoring',
  'Atmosphere',
  'Baseline mapping',
  'Borders',
  'Built environment',
  'Climate change',
  'Coastal areas',
  'Critical assets',
  'Cultural heritage assessment',
  'Detect & monitor hurricanes and typhoons',
  'Detect & monitor ice-risk at sea',
  'Detect & monitor illegal fishing',
  'Detect & monitor oil slicks',
  'Detect and monitor ground movement',
  'Detect and monitor wildfires',
  'Detect changes in glaciers',
  'Detect illegal forest activities',
  'Detect illegal mining activities',
  'Detect illegal or undesired crops',
  'Detect ships in critical areas',
  'Disasters & geohazards',
  'Energy',
  'Fisheries',
  'Food security and production',
  'Food security monitoring',
  'Forecast & map large waves',
  'Forecast & monitor ocean currents and drift',
  'Forecast & monitor ocean winds and waves',
  'Forecast and assess landslides',
  'Forecast weather',
  'Forecasting epidemics and diseases',
  'Forecasting sunlight exposure',
  'Forestry',
  'General crime & security surveillance assessment',
  'Health',
  'Identify hydrocarbon seeps in soil',
  'Infrastructure & installations',
  'Inland water',
  'Land ecosystems',
  'Land use',
  'Map & monitor hydroelectric energy',
  'Map & monitor solar energy (solar farms)',
  'Map & monitor transport networks',
  'Map & monitor wind energy (wind farms)',
  'Map and assess flooding',
  'Map disaster areas and multi hazard assessment',
  'Map fish shoals',
  'Map geological features',
  'Map line of sight visibility (land surface)',
  'Map seismic survey operations',
  'Marine ecosystem',
  'Marine pollution',
  'Measure and detect land surface change',
  'Meteorology',
  'Metocean',
  'Monitor and forecast air quality & emissions (fluxes)',
  'Monitor and forecast crop yields',
  'Monitor atmosphere composition',
  'Monitor coastal land cover',
  'Monitor construction & buildings',
  'Monitor critical infrastructure',
  'Monitor forest carbon content',
  'Monitor ice on rivers and lakes',
  'Monitor invasive species',
  'Monitor land & marine border incursions',
  'Monitor land cover and detect change assessment',
  'Monitor land pollution & waste management',
  'Monitor land use and land use change',
  'Monitor marine habitats',
  'Monitor mineral extraction',
  'Monitor ocean acidification',
  'Monitor ocean level & surface',
  'Monitor ocean quality & productivity',
  'Monitor oil rigs & flares',
  'Monitor pollution at sea',
  'Monitor ship movements',
  'Monitor transitional water bodies',
  'Monitor transport routes',
  'Monitor urban areas',
  'Monitor urban green & blue areas',
  'Monitor urban surroundings',
  'Monitor vegetation encroachment',
  'Monitor water depth or charting',
  'Monitor water use on crops and horticulture',
  'Monitor & assess snow cover',
  'Monitor sensitive risk areas',
  'Multiple',
  'Predict jellyfish',
  'Sea ice and icebergs',
  'Ships monitoring, detection and tracking',
  'Snow & ice',
  'Subsurface geology',
  'Topography and motion',
  'Waste',
];

// SEFMAP Stakeholder Valid Values (text labels only, matching import template)
export const SEFMAP_ORG_CATEGORY_OPTIONS = [
  'Service Provider',
  'Non-profit entity',
  'Public Authority',
  'Association/Cluster/Network',
  'Private sector',
  'Financial body/entity',
  'Research & Academia',
  'International Organisation',
  'EU',
  'Other',
];

export const SEFMAP_ROLE_IN_POLICY_OPTIONS = [
  'Maker',
  'Regulator',
  'Implementer',
  'Interest group',
  'Enforcer',
  'N/A',
];

export const SEFMAP_RELEVANCE_OPTIONS = ['High', 'Medium', 'Low'];

export const SEFMAP_STAKEHOLDER_THEME_OPTIONS = [
  'Food systems',
  'Environment and Biodiversity',
  'Carbon, Energy and Green Transition',
  'Sustainable Development Goals',
];

export const SEFMAP_ROLE_IN_PROJECT_OPTIONS = [
  'User',
  'Provider',
  'Multiplier',
  'Prime',
  'Stakeholder',
  'Early adopter',
];

export const SEFMAP_INVOLVEMENT_OPTIONS = [
  'Expressed Interest',
  'Involved',
  'Potentially',
];

export const SEFMAP_COUNTRY_OPTIONS = [
  'International',
  'EU',
  'UN',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antarctica',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bangladesh',
  'Belarus',
  'Belgium',
  'Belize',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Bulgaria',
  'Burkina Faso',
  'Cambodia',
  'Cameroon',
  'Canada',
  'China',
  'Colombia',
  'Croatia',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Ecuador',
  'Egypt',
  'Estonia',
  'Ethiopia',
  'Finland',
  'France',
  'Gabon',
  'Gaza Strip',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Greenland',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Republic of',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Lao People\'s Democratic Republic',
  'Latvia',
  'Lebanon',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestinian Territory, Occupied',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const EMPTY_SEFMAP_STAKEHOLDER = {
  id: '',
  org_name: '',
  short_description: '',
  country: '',
  website: '',
  org_category: '',
  role_in_policy: [],
  relevance: '',
  themes: [],
  sectors: [],
  application_areas: [],
};

export const SEFMAP_PROJECT_ID = 29020;

export const HUBSPOT_CSV_HEADERS = [
  'First Name',
  'Last Name',
  'Email',
  'Company Name',
  'Job Title',
  'Source of contact',
  'Lead Status',
  'Stakeholder Type',
  'Engagement type',
  'Contact owner',
  'Create Date',
  'Associated Note',
];

export const SEFMAP_XLSX_HEADERS = [
  'Name of Stakeholder Requirement',
  'Requirement category',
  'Stakeholder Requirement Description',
  'Stakeholder Priority',
  'Timescale of the Priority',
  'Biogeophysical Variables',
  'Spatial resolution',
  'Spatial coverage',
  'SEF Theme',
  'Application Area',
  'Sector',
  'Date Added',
  'Who added',
  'Context Added',
  'Weblink (URL)',
  'Other Remarks',
];

export const EMPTY_CONTACT = {
  id: '',
  first_name: '',
  last_name: '',
  email: '',
  company_name: '',
  job_title: '',
  source_of_contact: 'Events',
  lead_status: '',
  stakeholder_type: '',
  engagement_type: [],
  contact_owner: '',
  associated_note: '',
};

export const EMPTY_REQUIREMENT = {
  id: '',
  name: '',
  requirement_category: [],
  description: '',
  stakeholder_priority: 'High priority',
  timescale: 'Short term: 1-5 years',
  biogeophysical_variables: '',
  spatial_resolution: '',
  spatial_coverage: '',
  sef_themes: [],
  application_areas: [],
  sectors: [],
  other_remarks: '',
};

export const EMPTY_EVENT_INFO = {
  event_name: '',
  event_dates: { start: '', end: '' },
  event_website: '',
  event_organiser: '',
  event_type: 'Conference',
  colleague_name: [],
};

export const EMPTY_EVENT_REPORT = {
  esa_participants: '',
  sef_role: '',
  materials_presented: '',
  rationale: '',
  key_messages: '',
  key_stakeholders: '',
  follow_on: '',
  lessons_learned: '',
  other_points: '',
};
